### ISSUE TITLE
ModuleNotFoundError: No module named 'ensurepip'

### ISSUE THREAD

**Issue by ln-12** [robertguetzkow/blender-python-examples#1]
**Affected script or add-on**
Install Dependencies

**Describe the bug**
Can't install the add-on because of the error message below (ensurepip not found)

**Steps to reproduce**
Install the add-on via Blender's GUI
Blender version: 2.82a
OS: Windows 10

**Expected behavior**
No error occuring

```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\install-dependencies.py", line 185, in execute
    install_pip()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\install-dependencies.py", line 74, in install_pip
    import ensurepip
ModuleNotFoundError: No module named 'ensurepip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\install-dependencies.py", line 191, in execute
    self.report({"ERROR"}, err)
TypeError: EXAMPLE_OT_install_dependencies.report(): error with argument 2, "message" -  Function.message expected a string type, not ModuleNotFoundError

location: <unknown location>:-1
```

**Comment by robertguetzkow** [comment]
It seems that 2.82a on Windows is bundling pip, but doesn't have ensurepip. Will take a look if there's an elegant fix.

**Comment by robertguetzkow** [comment]
The error reporting is fixed. That was a very obvious mistake. I've missed it because Blender will display the stack trace in a popup anyway. Due to obligations the other part will be fixed within the next days. The approach will likely be to check if pip is already available and only then attempt to import ensurepip.

**Comment by ln-12** [comment]
When running Blender as administrator it now works as intended, thanks 👍

**Comment by robertguetzkow** [comment]
@ln-12 No problem, you're welcome!
